---
players:
  - gsis:
    name: NFL GSIS (Game Stats and Info Service)
    id_field: gsis_id
    active: true
    # Not usually updated with rookies until August-ish?
    required: false
    pattern: ^00\-\d{7}$
  - espn:
    name: ESPN
    id_field: espn_id
    active: false
    required: false
    pattern: ^\d{2,8}$
  - nffc:
    name: National Fantasy Football Championship
    id_field: nffc_id
    active: false
    required: false
    pattern: ^\d{2,8}$
  - pfr:
    name: Pro Football Reference
    id_field: pfr_id
    active: false
    required: false
    pattern: ^[A-Z]{1}[a-z]{1,3}[A-Z]{1}[a-z]{1,2}[0-9]{2}$
  - sleeper:
    name: Sleeper Fantasy
    id_field: sleeper_id
    active: false
    required: false
    pattern: ^\d{1,5}$
  - sportradar:
    name: Sportradar
    id_field: sportradar_id
    active: false
    required: false
    #uuid, lowercased
    pattern: ^[0-9a-f]{8}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{12}$
  - yahoo:
    name: Yahoo Fantasy
    id_field: yahoo_id
    active: true
    required: false
    pattern: ^\d{2,8}$